### ISSUE TITLE
importance_score计算过程是否应该使用原子操作？

### ISSUE THREAD

**Issue by archershot** [dexgfsdfdsg/LP-3DGS#5]
https://github.com/dexgfsdfdsg/LP-3DGS/blob/56978d72a68d1d681c5b8f67b166aaae8c1bf8a7/submodules/diff-gaussian-rasterization/cuda_rasterizer/forward.cu#L550C1-L550C52

这行代码表示对高斯所渲染像素的统计。按我的理解应该是使用atomicAdd进行统计，因为高斯的渲染是按像素并行的，可能出现不同线程同时对这个变量进行操作。 其他的模式bw/mx也是类似。

如果没有使用原子操作，其对总和的计算和最大值的计算会有不同程度的误差，理论上来讲对mw的影响是最低的。那么是否论文例出的对比结论还是成立的？

**Comment by dexgfsdfdsg** [comment]
Yes, that's correct. In our experiment, we did use atomic operations. The code was prepared quickly at the time of submission and old version of code was uploaded, but I have since uploaded the atomic max score, which you can find in "forward.cu". Regarding your concern about the potential influence on results, we compared the data using both versions of the code, and the quantitative differences were minimal, not affecting the experimental conclusions.

**Comment by archershot** [comment]
> Yes, that's correct. In our experiment, we did use atomic operations. The code was prepared quickly at the time of submission and old version of code was uploaded, but I have since uploaded the atomic max score, which you can find in "forward.cu". Regarding your concern about the potential influence on results, we compared the data using both versions of the code, and the quantitative differences were minimal, not affecting the experimental conclusions.

ok, thx!
